# Site settings
baseurl = "https://widschicago.org/" # Change this to the base url after netlify deploy, e.g. "https://cardiff2019.satrdays.org/"
languageCode = "en-us"
title = "WiDS Chicago "
theme = ["hugo-satrdays-theme", "hugo-agency-theme"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Disable taxonomies that are not used https://discourse.gohugo.io/t/found-no-layout-for-taxonomyterm-language-en-output-format-html/16376
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "WiDS Chicago "
  description = "A conference showcasing womxn data scientists in Chicago"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = ["css/satrday.css"]
  custom_js  = []
  favicon    = "img/wids_icon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "satRday"
    # Optional logo as brand stored in img/
    logo = "wids_chicago_logo.jpg"
    services = "About"
    portfolio = "Talks"
    hackathon = "Datathon"
    eventbrite = "Register"
    schedule = "Schedule"
    team = "People"
    contact = "Get involved"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "https://widschicago.org/#hackathon"
      name = "Datathon"
      weight = 10

    [[menu.postpend]]
      url = "http://widsconference.org/"
      name = "widsconference.org"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Women in Data Science Chicago"
    subtitle = "A conference showcasing womxn data scientists in Chicago on Friday, March 11th"
    bg = true
    buttonText = "Tell me more"


  # About [Services] section
  [params.services]
    enable = true
    title = "About"
    subtitle = "Conference Details"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-clock-o"
      title = "Details"
      description = "Friday, March 11, 5:00-7:30 PM CST"
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Hands on"
      description = "Participate in a Datathon-- creating models to predict building energy consumption"
      url = "https://widschicago.org/#hackathon"

    [[params.services.row.list]]
      icon = "fa-universal-access"
      title = "Networking"
      description = "Opportunity to expand your professional network"
      url = "https://widschicago.org/#schedule"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-graduation-cap"
      title = "Learning"
      description = "Gain knowledge from your peers and experienced professionals"
      url = "https://widschicago.org/#team"

    [[params.services.row.list]]
      icon = "fa-money"
      title = "No Cost!"
      description = "Yep, that's right: Free!"
      url = "https://widschicago.org/#eventbrite"

    [[params.services.row.list]]
      icon = "fa-users"
      title = "Community Led"
      description = "Community organized, community focused"
      url = "https://widschicago.org/#team"


  # Register section
  # You only need ONE of these active
  [params.tito]
    enable = false
    title = "Register"
    bg = true
    accountevent = "ultimateconf/2013"
      # Go to https://ti.to/ and find the account (under your user) and event pair string e.g. "cardiff-satrday/2018"
      # include botht the account and event in a string, seperated by /, with no spaces

  [params.eventbrite]
    enable = true
    title = "Register"
    subtitle = "WiDS Chicago on 3/11"
    bg = true
    eid = "272855176177"
      # Go to https://www.eventbrite.co.uk/support/articles/en_US/How_To/how-to-sell-eventbrite-tickets-registrations-on-your-website-using-embeddable-widgets?lg=en_GB
      # Follow instructions to discover your 'Website Integration' embeddable iframe
      # Take ONLY the numeric string between "eid=" and "&ref=etckt"
      # Supply this string as the value to `eid` above

  [params.mailinglist]
    enable = true
    title = "Sign up for our Mailing List!"
    subtitle = "More information about WiDS Chicago future events!"
    bg = true


  [params.tickettailor]
    enable = false
    title = "Register"
    bg = true
    eventviewid = "162430"
      # Go to www.tickettailor.com and open your event page
      # Note the number at the end of the url e.g. https://www.tickettailor.com/event/view/id/162430
      # Supply the number ONLY in `eventviewid`

  # Call for papers section
  [params.callforpapers]
    enable = false
    title = "Call For Papers"
    bg = false
    CfSpage = "/test3490"
      # Go to Organizer > My Events > Dashboard and copy the "CfS Page" string into the `CfSpage` value
    dates = "09 Aug - 21 Sep 2018"

  # Hackathon section
  [params.hackathon]
    enable = false
    bg = false
    title = "Datathon"
    subtitle="Participate in a datathon for social good!"
    brief1="</br> WiDS Chicago Datathon Workshop is an independent event organized by WiDS Ambassadors in Chicago to coincide with the annual Women in Data Science (WiDS) Worldwide Datathon."
    location= "__Dates__: The datathon will be held from January 7th-February 26th, 2022 on Kaggle with winners announced in early March 2022."
    #dates = "__Registration__: In addition to registering for the Datathon Kickoff in the Eventbrite below, you must register for the  <a href= 'https://airtable.com/shrLE1J7hVxuYAILv' > WiDS @ Stanford datathon </a> as well. "
    times= "__Datathon Kickoff!: Workshop and Team Formation__: On January 21th we will be holding an introduction to Kaggle workshop that will also provide time to form teams. Register for the event on the Eventbrite widget below."

    website_name=""
    website_url=""
    eid = "231135371117"


  # Talk [Portfolio] section
  [params.portfolio]
    enable =false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Talks"
    subtitle = "Who's saying what"
    bg = true

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"

  # Schedule section
  [params.schedule]
    enable = true
    title = "Schedule"
    bg = false

  # Important Dates [About] section
  [params.about]
    enable = false
    title = "Important Dates"
    subtitle = "Be prepared!"
    endpoint = "Conference"


  [params.home]
    enable = true
    title = "Mission"
    bg = true


    # The events will be listed from the top to the bottom.
    # All images are stored under 'static/img/about'.
    # Replace them with your own.
    [[params.about.events]]
      img = "1.jpg"
      date = "First Date"
      title = "Initial Announcement"
      description = "We're organising a conference!"

    [[params.about.events]]
      img = "2.jpg"
      date = "Second Date"
      title = "Early Bird Ticket Sales"
      description = "Early round of tickets now available at discount"

    [[params.about.events]]
      img = "3.jpg"
      date = "Third Date"
      title = "Call For Papers"
      description = "Submissions for speakers are now open!"

    [[params.about.events]]
      img = "4.jpg"
      date = "Fourth Date"
      title = "Call For Papers Ends"
      description = "Cut off date for speaker submissions"

  # Location section
  [params.location]
    enable = false
    title = "Location"
    bg = true
  iframesrc= "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2970.767769736558!2d-87.62730558455895!3d41.876342679222326!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e2ca21507764f%3A0x44cc0732016145b4!2sRoosevelt%20University!5e0!3m2!1sen!2sus!4v1578328289404!5m2!1sen!2sus"

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "<br/><br/>Team"
    subtitle = "The people putting it together"
    speakers_subtitle = ""
    bg = false
    description = ""
    speakers = "Speakers <br/>"
    mentors = "Datathon Mentors"

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "Abby_headshot.jpg"
      name = "Abby Smith"
      position = "WiDS Ambassador"
      # For bio markdown and even multiline strings are available.
      bio = """PhD Candidate in Statistics <br/> Northwestern Women in Statistics (WIST)"""
      social = [
        ["fa-twitter", "https://twitter.com/flabbysmith"],
        ["fa-github", "https://github.com/abbylsmith"],
        ["fa-linkedin", "https://www.linkedin.com/in/abby-smith-55312a200/"],
        ["fa-rss", "https://abbylsmith.me"]
      ]

    [[params.team.members]]
      img = "Jane_headshot.jpg"
      name = "Jane Zanzig"
      position = "WiDS Ambassador"
      bio = """Senior Data Scientist and Designer <br/> IDEO"""
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/jane-zanzig/"]
      ]

    [[params.team.members]]
      img = "Abby_stevens_headshot.jpg"
      name = "Abby Stevens"
      position = "WiDS Ambassador"
      bio = """PhD Candidate in Statistics <br/> University of Chicago"""
      social = [
        ["fa-twitter", "https://twitter.com/abbystvns"],
        ["fa-github", "https://github.com/abbystvns"],
        ["fa-linkedin", "https://www.linkedin.com/in/abbyestevens/"],
        ["fa-instagram", "https://www.instagram.com/abbbyst/"],
        ["fa-rss", "https://abbystevens.com"]
      ]
         [[params.team.members]]
      img = "Mena_headshot.jpg"
      name = "Mena Whalen"
      position = "WiDS Ambassador"
      bio = """Assistant Professor of Statistics <br/> Loyola University of Chicago"""
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/mena-whalen-07290b174"],
        ["fa-rss", "https://menawhalen.com/"]
      ]



      [[params.team.members]]
      img = "angelina_headshot.jpg"
      name = "Angelina Leigh"
      position = "WiDS Ambassador"
      bio = """Data Scientist <br/> Hitachi Solutions"""
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/angelina-maria-leigh-254506134/"],

      ]



      [[params.team.members]]
      img = "devanshi_headshot.jpg"
      name = "Devanshi Verma"
      position = "WiDS Ambassador"
      # For bio markdown and even multiline strings are available.
      bio = """Data Scientist <br/> CVS Health"""
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/devanshiverma/"],
        ["fa-github", "https://thisisdevanshi.github.io/"]
      ]

      [[params.team.members]]
      img = "zaynaib_headshot.jpg"
      name = "Zaynaib Giwa"
      position = "WiDS Ambassador"
      # For bio markdown and even multiline strings are available.
      bio = """Data Analyst <br/> Invisible Institute"""
      social = [
        ["fa-linkedin", "https://www.linkedin.com/in/zaynaib-ola-giwa"],
        ["fa-github", "https://zaynaib.github.io/"]
      ]



  # Client section
  [params.clients_list]
    enable = true
    # Possibility to center items
    #center = true
    # Optional client title specifying the involvement
    title = "Sponsors"
    bg = true

    # All the clients' logos are stored under 'static/img/logos'.
    # Replace them with your clients's logos.
    # Suggestion: .svg in the size of 280px*80px looks good

      [[params.clients]]
      logo = "roosevelt-logo.jpg"
      link = "https://www.roosevelt.edu/"

        [[params.clients]]
      logo = "CRUG_logo.png"
      link = "https://chicago-r-user-group.github.io/"


    [[params.clients]]
      logo = "dsi.png"
      link = "http://datascience.uchicago.edu/"


    [[params.clients]]
      logo = "uchi-stat.png"
      link = "https://stat.uchicago.edu//"

    [[params.clients]]
      logo = "uchi_cs_logo.png"
      link = "https://cst.uchicago.edu//"


    [[params.clients]]
      logo = "loyola_uni_logo.png"
      link = "https://www.luc.edu/math/index.shtml"


  #[[params.clients]]
      #logo = "chicago_ASA.jpg"
      #link = "https://community.amstat.org/chicagochapter/home"

  [[params.clients]]
      logo = "WIST_logo.png"
      link = "https://www.statistics.northwestern.edu/research/women-in-statistics/"





  [params.diversity]
    enable = true
    title = "WiDS Code of Conduct"
    bg = true


  # Contact section
  [params.contact]
    enable = true
    title = "Have a question about WiDS Chicago ? "
    buttonText = "Send message!"
    #netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "als1@u.northwestern.edu"

    # Success and error message overwrite for async contact form
    thanks = "Thank you for awesomely contacting WiDS Chicago."
    error = "Message could not be send. Please contact us at als1@u.northwestern.edu instead."

    [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = false
    copyright = "Published under the Apache License 2.0."


